baseURL: https://public-jun.github.io/
languageCode: ja
title: Get stronger one day at a time.
theme:  PaperMod
googleAnalytics: G-1VL8593G1N
enableRobotsTXT: true

params:
  homeInfoParams:
    Title: Hi there wave
    Content: これは1日ひとつ強くなる42Tokyo生の個人ブログです。
  # code cp button
  ShowCodeCopyButtons: true

  customCSS:
    - css/custom.css

  socialIcons:
        - name: github
          url: "https://github.com/public-jun"
        - name: twitter
          url: "https://twitter.com/public_jun"

  ShowShareButtons: true

  comments: true

  description: jnakahod's blog
  images:
  - blog-card-pic.png
  title: My cool site

menu:
  main:
    - identifier: works
      name: Works
      url: /works/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4

# Search Page
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

enableEmoji: true

# Taxonomy Default
taxonomies:
  category: categories
  tag: tags
  series: series

# sitemap set (google search)
