baseURL: https://public-jun.github.io/
languageCode: ja
title: Get stronger one day at a time.
theme:  PaperMod
googleAnalytics: G-1VL8593G1N
enableRobotsTXT: false

#Show Table of Contents (Toc) on blog post
ShowToc: true
TocOpen: true

params:
  homeInfoParams:
    Title: Hi there wave
    Content: これは1日ひとつ強くなる42Tokyo生の個人ブログです。
  # code cp button
  ShowCodeCopyButtons: true

  customCSS:
    - css/custom.css

  socialIcons:
        - name: github
          url: "https://github.com/public-jun"
        - name: twitter
          url: "https://twitter.com/public_jun"

  ShowShareButtons: true

  defaultTheme: auto # to switch between dark or light according to browser theme

  ShowBreadCrumbs: true

  ShowPostNavLinks: true


  comments: true

  description: 1日ひとつ強くなる42Tokyo生の個人ブログです。
  images:
  - first-blog-card-fs8.png
  title: jnakahod's blog


menu:
  main:
    # - identifier: works
    #   name: Works
    #   url: /works/
    #   weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 3
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 4
    - identifier: search
      name: Search
      url: /search/
      weight: 5

# Search Page
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

enableEmoji: true

# Taxonomy Default
taxonomies:
  category: categories
  tag: tags
  series: series

